// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Base jetable utilisée par `prisma migrate dev` / `migrate diff` pour
    // comparer les migrations au schéma. Facultative.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
