// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIKM9Gt194VnziSB0sGuxsK-EUlz6URww',
    appId: '1:326315783454:web:2be0a5dba079a86d5a050f',
    messagingSenderId: '326315783454',
    projectId: 'sahel-academy',
    authDomain: 'sahel-academy.firebaseapp.com',
    storageBucket: 'sahel-academy.firebasestorage.app',
    measurementId: 'G-SSCDFSNSYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNr8X8Guia8tv-5oCIWJzhAtpmj98ppY',
    appId: '1:326315783454:android:0cbc0414ab085c195a050f',
    messagingSenderId: '326315783454',
    projectId: 'sahel-academy',
    storageBucket: 'sahel-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqEV_1ayJPfzyzJlBe4o2mRq2hr0JZi0',
    appId: '1:326315783454:ios:406db341f9b298d75a050f',
    messagingSenderId: '326315783454',
    projectId: 'sahel-academy',
    storageBucket: 'sahel-academy.firebasestorage.app',
    iosBundleId: 'com.sahelacademy.app',
  );
}
